---
- hosts: dev
  user: aniket
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
          ############inatall Apache2#############
        - name: Install Apache 
          apt: name=apache2 update_cache=yes state=present
        - name: start Apache
          action: service name=apache2 state=started

          ###########install git#################
        - name: Install git
          action: apt pkg=git state=present

          ############install java#############
        - name: Install java11
          action: apt pkg=openjdk-11-jdk state=present
       
        ############install tomcat##########
        - name: create directory
          action: file path=/home/aniket/tomcat state=directory
        - name: Install tomcat
          action: get_url url=https://downloads.apache.org/tomcat/tomcat-9/v9.0.73/bin/apache-tomcat-9.0.73.zip dest=/home/aniket/tomcat
        - name: install unzip
          action: apt name=unzip state=present
        - name: unzip tomcat
          action: unarchive src=/home/aniket/tomcat/apache-tomcat-9.0.73.zip dest=/home/aniket/tomcat remote_src=yes

        - name: giving ownership to tomcat
          action: file path=/home/aniket/tomcat/apache-tomcat-9.0.73 state=directory owner=aniket group=aniket mode=777 recurse=yes
        - name: Start tomcat
          command: "nohup /home/aniket/tomcat/apache-tomcat-9.0.73/bin/startup.sh"

       ##############install tree##############
        - name: Install tree
          action: apt name=tree state=present
