---
- hosts: dev
  user: aniket
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
          ############uninstall Apache2#############
        - name: uninstall Apache
          apt: name=apache2 update_cache=yes state=absent

          ###########uninstall git#################
        - name: uninstall git
          action: apt pkg=git state=absent

          ############uninstall java#############
        - name: uninstall java11
          action: apt pkg=openjdk-11-jdk state=absent

        ############install tomcat##########
        - name: Start tomcat
          command: "nohup /home/aniket/tomcat/apache-tomcat-9.0.73/bin/shutdown.sh"

       ##############uninstall tree##############
        - name: uninstall tree
          action: apt name=tree state=absent


